'use strict';
const $=id=>document.getElementById(id), token=document.querySelector('meta[name="app-token"]').content;
let selected='', devices=[], page='overview', busy=false, previousCPU=null, currentDir='/userdata', listSerial='', stopped=false;
const titles={overview:['设备概览','查看开发板的运行状态与资源使用情况'],files:['文件管理','浏览设备目录，上传和下载工作文件'],logs:['系统日志','定位设备运行过程中的问题'],terminal:['命令控制台','通过 ADB 执行 Linux 命令'],services:['服务与维护','管理监控服务与设备常用操作']};
const formatBytes=n=>{if(!Number.isFinite(n))return '—'; const units=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<3){n/=1024;i++}return `${n.toFixed(i>1?1:0)} ${units[i]}`};
function notice(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'';$('notice').hidden=false}
function clearNotice(){$('notice').hidden=true}
async function request(path,data={},options={}){const response=await fetch(path,{method:'POST',headers:{'X-App-Token':token,'Content-Type':'application/json'},body:JSON.stringify(data),...options});if(!response.ok){let message;try{message=(await response.json()).error}catch{message=`请求失败 (${response.status})`}throw Error(message)}return response}
async function api(path,data={}){return (await request(path,{serial:selected,...data})).json()}
async function task(fn,button){if(busy){notice('正在执行其他操作，请稍后。');return}busy=true;$('deviceSelect').disabled=true;if(button)button.disabled=true;clearNotice();try{await fn()}catch(e){notice(e.message||'连接中断，请重新打开管理软件。',true)}finally{busy=false;$('deviceSelect').disabled=false;if(button)button.disabled=false}}
function requireDevice(){if(!selected)throw Error('请先连接并选择一个在线设备。')}
function confirmAction(title,text){return new Promise(resolve=>{const dialog=$('confirmDialog');$('confirmTitle').textContent=title;$('confirmText').textContent=text;const done=value=>{dialog.close();dialog.oncancel=null;resolve(value)};$('confirmYes').onclick=()=>done(true);$('confirmNo').onclick=()=>done(false);dialog.oncancel=e=>{e.preventDefault();done(false)};dialog.showModal()})}
function resetData(){previousCPU=null;listSerial='';$('cpu').textContent='—';$('memory').textContent='—';$('temperature').textContent='—';$('uptime').textContent='—';$('memoryDetail').textContent='等待设备数据';$('load').textContent='平均负载 —';$('memoryBar').style.width='0';$('cpuBar').style.width='0';$('kernel').textContent='—';$('network').textContent='—';$('serialText').textContent=selected||'—';$('disks').textContent='连接后显示根目录与 userdata 分区';$('hostname').textContent=selected?'正在读取设备…':'连接你的泰山派';$('osLabel').textContent='从一条 USB 数据线开始，掌握设备运行状态。';$('fileRows').replaceChildren();$('fileCount').textContent='';$('logOutput').textContent='点击读取日志';$('commandOutput').textContent='等待执行命令…';$('serviceOutput').textContent='点击查看状态';$('monitorBadge').textContent='待检测';$('identityTag').textContent='OFFLINE';$('updated').textContent='等待采样'}
function setBadge(online,text){$('statusBadge').textContent=text;$('statusBadge').className='badge'+(online?' online':'')}
function renderDevices(items){devices=items;const select=$('deviceSelect');select.replaceChildren();const empty=document.createElement('option');empty.value='';empty.textContent=items.length?'请选择设备':'未发现设备 · 请连接 USB 数据线';select.append(empty);items.forEach(d=>{const option=document.createElement('option');option.value=d.serial;option.textContent=`${d.transport} · ${d.serial} · ${d.state==='device'?'在线':d.state}`;option.disabled=d.state!=='device';select.append(option)});let next=items.some(d=>d.serial===selected&&d.state==='device')?selected:(items.find(d=>d.state==='device')?.serial||'');if(next!==selected){selected=next;resetData()}select.value=selected;setBadge(!!selected,selected?'ADB 已连接':'未连接设备');$('connectionHint').textContent=items.some(d=>d.state==='unauthorized')?'设备尚未授权，请在设备端确认 USB 调试授权。':items.some(d=>d.state==='offline')?'有设备处于 offline，请重新插拔数据线后刷新。':selected?'已连接。所有操作仅针对当前选中的设备。':'USB 连接后刷新设备列表；如果始终为空，请检查数据线、ADB 驱动和板端 adbd 服务。';$('transport').textContent=items.find(d=>d.serial===selected)?.transport==='USB'?'USB 已连接':selected?'网络 ADB':'ADB 管理'}
async function refreshDevices(){const data=await api('/api/devices');renderDevices(data.devices);if(selected&&page==='overview')await status()}
async function status(){if(!selected)return;const serial=selected;try{const data=await api('/api/status');if(serial!==selected)return;setBadge(true,'设备在线');$('hostname').textContent=data.hostname;$('osLabel').textContent=data.os;$('serialText').textContent=serial;$('kernel').textContent=data.kernel;$('network').textContent=data.network||'未获取到 IPv4 地址';$('identityTag').textContent='CONNECTED';$('temperature').textContent=data.temperature===null?'不支持':`${data.temperature.toFixed(1)} °C`;const memPercent=data.memoryTotal?100*data.memoryUsed/data.memoryTotal:0;$('memory').textContent=`${memPercent.toFixed(1)}%`;$('memoryDetail').textContent=`${formatBytes(data.memoryUsed)} / ${formatBytes(data.memoryTotal)}`;$('memoryBar').style.width=`${Math.min(100,memPercent)}%`;if(previousCPU){const total=data.cpuTotal-previousCPU.total,idle=data.cpuIdle-previousCPU.idle;if(total>0){const usage=Math.min(100,Math.max(0,100*(1-idle/total)));$('cpu').textContent=`${usage.toFixed(1)}%`;$('cpuBar').style.width=`${usage}%`}}previousCPU={total:data.cpuTotal,idle:data.cpuIdle};const minutes=Math.floor(data.uptime/60);$('uptime').textContent=minutes>=1440?`${Math.floor(minutes/1440)} 天 ${Math.floor(minutes%1440/60)} 时`:`${Math.floor(minutes/60)} 时 ${minutes%60} 分`;$('load').textContent=`平均负载 ${data.load.join(' / ')}`;$('monitorBadge').textContent=data.monitorAvailable?'已检测到脚本':'未安装脚本';$('disks').replaceChildren();data.disks.forEach(d=>{const row=document.createElement('div');row.className='disk-row';const label=document.createElement('div');label.className='disk-label';const mount=document.createElement('span');mount.textContent=d.mount;const percent=document.createElement('span');percent.textContent=d.percent;label.append(mount,percent);const meter=document.createElement('div');meter.className='meter';const fill=document.createElement('i');fill.style.width=`${Math.max(0,Math.min(100,parseFloat(d.percent)||0))}%`;meter.append(fill);const summary=document.createElement('p');summary.textContent=`已用 ${formatBytes(d.used)} / 共 ${formatBytes(d.total)}`;row.append(label,meter,summary);$('disks').append(row)});$('updated').textContent=`更新于 ${new Date().toLocaleTimeString('zh-CN')}`}catch(e){previousCPU=null;setBadge(false,'连接中断');$('updated').textContent='数据已过期';throw e}}
document.querySelectorAll('[data-page]').forEach(button=>button.onclick=()=>{page=button.dataset.page;document.querySelectorAll('.page').forEach(el=>el.hidden=el.id!==`page-${page}`);document.querySelectorAll('.nav').forEach(el=>el.classList.toggle('active',el===button));$('pageTitle').textContent=titles[page][0];$('pageSubtitle').textContent=titles[page][1];clearNotice();if(page==='overview'&&selected&&!busy)task(status);});
$('refreshDevices').onclick=e=>task(refreshDevices,e.currentTarget);
$('deviceSelect').onchange=()=>{selected=$('deviceSelect').value;resetData();setBadge(!!selected,selected?'ADB 已连接':'未连接设备');if(selected)task(status)};
$('networkToggle').onclick=()=>{$('networkForm').hidden=!$('networkForm').hidden};
$('connect').onclick=e=>task(async()=>{const result=await api('/api/connect',{address:$('address').value});selected=$('address').value.trim();resetData();renderDevices(result.devices);notice(result.message);if(selected)await status()},e.currentTarget);
function join(dir,name){return `${dir==='/'?'':dir}/${name}`}
async function loadFiles(path){requireDevice();const data=await api('/api/files',{path});currentDir=data.path;listSerial=selected;$('remotePath').value=data.path;$('fileRows').replaceChildren();data.files.forEach(file=>{const row=document.createElement('tr');const name=document.createElement('td');const icon=document.createElement('span');icon.className='file-icon';icon.textContent=file.type==='d'?'▰':file.type==='l'?'↗':'▤';name.append(icon);if(file.type==='d'){const btn=document.createElement('button');btn.className='file-link';btn.textContent=file.name;btn.onclick=()=>task(()=>loadFiles(join(currentDir,file.name)),btn);name.append(btn)}else{name.append(document.createTextNode(file.name))}const size=document.createElement('td');size.textContent=file.type==='d'?'—':formatBytes(file.size);const modified=document.createElement('td');modified.textContent=new Date(file.modified*1000).toLocaleString('zh-CN');const action=document.createElement('td');if(file.type!=='d'){const btn=document.createElement('button');btn.className='text-button';btn.textContent='下载';btn.onclick=()=>task(async()=>{requireDevice();const response=await request('/api/download',{serial:selected,path:join(currentDir,file.name)});saveBlob(await response.blob(),file.name);notice('下载完成，请查看浏览器下载目录。')},btn);action.append(btn)}row.append(name,size,modified,action);$('fileRows').append(row)});if(!data.files.length){const row=document.createElement('tr');const cell=document.createElement('td');cell.colSpan=4;cell.className='empty-cell';cell.textContent='此目录为空';row.append(cell);$('fileRows').append(row)}$('fileCount').textContent=data.limited?'仅显示前 1000 项，请打开更具体的目录。':`${data.files.length} 个项目`}
$('pathForm').onsubmit=e=>{e.preventDefault();task(()=>loadFiles($('remotePath').value))};
$('parentDir').onclick=()=>task(()=>loadFiles(currentDir.substring(0,currentDir.lastIndexOf('/'))||'/'));
$('uploadButton').onclick=()=>{if(!selected){notice('请先选择设备。',true);return}if(listSerial!==selected){notice('请先打开目标目录，再上传文件。',true);return}$('uploadFile').click()};
$('uploadFile').onchange=async()=>{const file=$('uploadFile').files[0];$('uploadFile').value='';if(!file)return;const serial=selected,dest=join(currentDir,file.name);if(file.size>512*1024*1024){notice('单个文件上限为 512 MB。',true);return}if(!await confirmAction('确认上传文件',`设备：${serial}\n目标：${dest}\n大小：${formatBytes(file.size)}\n如果存在同名文件，会被覆盖。`))return;task(async()=>{if(serial!==selected)throw Error('设备已切换，请重新选择上传文件。');notice('正在上传，请等待…');const result=await request(`/api/upload?serial=${encodeURIComponent(serial)}&path=${encodeURIComponent(dest)}&confirm=yes`,{}, {headers:{'X-App-Token':token,'Content-Type':'application/octet-stream'},body:file});const data=await result.json();await loadFiles(currentDir);notice(data.message)})};
function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
$('readLogs').onclick=e=>task(async()=>{requireDevice();$('logOutput').textContent=(await api('/api/logs',{kind:$('logKind').value})).output||'暂无日志'},e.currentTarget);
$('saveLogs').onclick=()=>saveBlob(new Blob([$('logOutput').textContent],{type:'text/plain;charset=utf-8'}),`taishanpi-${$('logKind').value}.log`);
document.querySelectorAll('[data-command]').forEach(btn=>btn.onclick=()=>{$('command').value=btn.dataset.command;$('command').focus()});
$('commandForm').onsubmit=e=>{e.preventDefault();task(async()=>{requireDevice();if(!$('commandConfirm').checked)throw Error('请先勾选命令执行确认。');$('commandOutput').textContent='执行中…';const result=await api('/api/command',{command:$('command').value,confirm:true});$('commandOutput').textContent=`$ ${$('command').value}\n\n${result.output}\n[退出码 ${result.code}]`})};
document.querySelectorAll('[data-service]').forEach(btn=>btn.onclick=async()=>{const serial=selected,action=btn.dataset.service;if(!serial){notice('请先选择设备。',true);return}if(action!=='status'&&!await confirmAction('确认服务操作',`将在 ${serial} 上${action==='start'?'启动':'停止'}网络健康监控服务。`))return;task(async()=>{if(serial!==selected)throw Error('设备已切换，请重新操作。');$('serviceOutput').textContent=(await api('/api/service',{action,confirm:true})).output||'操作已完成'},btn)});
$('reboot').onclick=async()=>{const serial=selected;if(!serial){notice('请先选择设备。',true);return}if(await confirmAction('重启泰山派',`确定重启 ${serial}？运行中的服务和 ADB 连接会中断。`))task(async()=>{if(serial!==selected)throw Error('设备已切换，请重新操作。');notice((await api('/api/reboot',{confirm:true})).message);setBadge(false,'正在重启');previousCPU=null})};
$('quit').onclick=async()=>{if(await confirmAction('退出管理软件','这会关闭本机管理服务。设备上的程序会继续运行。'))task(async()=>{await api('/api/quit');stopped=true;notice('管理服务已退出，可以关闭此页面。');setBadge(false,'软件已退出')})};
setInterval(()=>{if(stopped||busy||!selected||page!=='overview'||document.hidden)return;task(status)},5000);
task(refreshDevices);
